import { describe, expect, it } from 'vitest'
import { createOrderSchema, patchOrderSchema } from './orders.schema.js'
import { toColumns, toOrder } from './orders.mapper.js'
describe('order contract', () => {
 it('defaults fields and rejects identity', () => { const input={category:'agent',name:' Book ',amount:120.5,productCategories:['book']}; expect(createOrderSchema.parse(input)).toMatchObject({name:'Book',currency:'TWD',shippingMethod:'',trackingNumber:''}); expect(()=>createOrderSchema.parse({...input,userId:crypto.randomUUID()})).toThrow() })
 it('rejects invalid patches', () => { expect(()=>patchOrderSchema.parse({})).toThrow(); expect(()=>patchOrderSchema.parse({id:crypto.randomUUID()})).toThrow() })
 it('rejects removed payment detail fields', () => { const input={category:'agent',name:'Book',amount:120.5,productCategories:['book']}; expect(()=>createOrderSchema.parse({...input,balanceDue:10})).toThrow(); expect(()=>patchOrderSchema.parse({paymentDueDate:'2026-08-20'})).toThrow() })
 it('accepts only HTTP and HTTPS product URLs', () => { const input={category:'agent',name:'Book',amount:120.5,productCategories:['book']}; expect(createOrderSchema.parse({...input,productUrl:'https://example.com/item/1'}).productUrl).toBe('https://example.com/item/1'); expect(()=>createOrderSchema.parse({...input,productUrl:'javascript:alert(1)'})).toThrow() })
 it('maps rows without ownership or legacy payment details', () => { const now=new Date(); const order=toOrder({id:crypto.randomUUID(),user_id:crypto.randomUUID(),category:'agent',name:'Book',platform:'',product_url:'',status:'AWAITING_SHIPMENT',amount:'120.50',currency:'TWD',is_paid:false,balance_due:'10',order_date:null,payment_due_date:'2026-08-20',estimated_ship_date:null,estimated_arrival_date:null,is_preorder:false,product_categories:['book'],tracking_number:'EN123456789JP',shipping_method:'日本郵便 EMS',notes:'',created_at:now,updated_at:now}); expect(order).toMatchObject({amount:120.5,productUrl:'',productCategories:['book'],trackingNumber:'EN123456789JP',shippingMethod:'日本郵便 EMS'}); expect(order).not.toHaveProperty('userId'); expect(order).not.toHaveProperty('balanceDue'); expect(order).not.toHaveProperty('paymentDueDate') })
 it('maps logistics fields to database columns and preserves empty strings', () => { expect(toColumns({shippingMethod:'日本郵便 EMS',trackingNumber:'EN123456789JP'})).toEqual({shipping_method:'日本郵便 EMS',tracking_number:'EN123456789JP'}); expect(toColumns({shippingMethod:'',trackingNumber:''})).toEqual({shipping_method:'',tracking_number:''}) })
})
